### PR TITLE
fix play speed changing (#299)

### PR DESCRIPTION
**Pull request by NoMoKeTo**
https://github.com/popcornmix/omxplayer/issues/299

### CODE REVIEW

**Comment by Ruffio** [comment]
@NoMoKeTo could you please fix the conflicts, so it can be merged?

**Comment by NoMoKeTo** [comment]
This was over a year ago and it was a one-line commit only. If there are conflicts now please fix them yourself as a i don't have time for it at the moment.

**Comment by Ruffio** [comment]
@popcornmix, any thoughts on this one?

**Comment by popcornmix** [comment]
I believe https://github.com/popcornmix/omxplayer/commit/b1ad23ec682c5ee6761e77a990fb988a1d61b3fa was an equivalent fix.
If someone has a sample file and instructions that shows this PR is still needed then it can be reopened.

**Pull request closed without merging**
