### PR TITLE
Autotools Build System

### PR DESCRIPTION
**Pull request by ashegoulding**
### Building (Cross-compile)
    ./bootstrap.sh
    ./configure --host=(cross-compiler prefix)
    make
    make install
There are packages need to be installed in cross-compile sandbox prior to build the project. Refer to **Building on RPI**

#### Building on RPI
    ./bootstrap
    ./configure
    make -j5
    make install

Tested on: Fedora 22
Doesn't work on: RASPBIAN

#### Packages required
When building on RPI, not cross-compiling. You need to set up sandbox and compile these projects one by one for RPI host.
Or compile it from RPI, which is the easiest way. But more test is needed since the project is C++0x and the compilation fails on certain old system images(like on RASPBIAN I tested)

##### Debian
* libpcre3-dev libdbus-1-dev libboost-all-dev libfreetype6-dev autoconf automake pkg-config

##### RPM
* pcre-devel dbus-devel boost-devel freetype-devel autoconf automake pkg-config

### TODO
rename **danu_omxplayer** to **omxplayer** in *src/Makefile.am*. Then it is good to go.

### CODE REVIEW

**Comment by popcornmix** [comment]
Thanks this looks interesting.
Raspbian is the most commonly used system, so reliable instructions for building from there will be needed before merging. There should be a raspbian jessie image out in the next few weeks, so that may make things easier (as it has a newer gcc).
For raspbian wheezy I don't mind if there are manual instructions to upgrade gcc, like [https://somewideopenspace.wordpress.com/2014/02/28/gcc-4-8-on-raspberry-pi-wheezy](these).

**Comment by ashegoulding** [comment]
On it. Updating README and stuff.

Wish I can get rid of cross compiling. It is far from pretty OK, it's utter havoc. Why don't we, just give up on how to work on cross-compiling and let users compile it in RPI? Experts would know how to do it anyway without any guidance. What say you? And not to mention that it takes less than 5 mins to compile with '-j5' option and 30 mins including FFmpeg.

### TODO
#### Guide
* FFmpeg compilation
* Upgrading GCC on Raspbian (lower than jessie)
* omxplayer compilation

#### Some Changes
* Removal of unnecessary files
* rid of "danu" prefixes


'Til nt.

**Comment by popcornmix** [comment]
I think cross compiling can be handled elsewhere. Perhaps a link to:
https://github.com/skgsergio/rpi-buildenv

**Comment by Ruffio** [comment]
@ashegoulding will you update this one?

**Comment by ashegoulding** [comment]
@Ruffio No. We're leaving this project. rpi project was just putting on a show and we couldn't make anything lucrative out it. omxplayer is already a bit of mess anyway.
Sorry.

**Pull request closed without merging**
