### PR TITLE
Fix dbus message handling problems

### PR DESCRIPTION
**Pull request by fabled**
- make sure dbus messages are released after handling
- return error to unknown method calls to avoid timeouts

### CODE REVIEW

**Comment by popcornmix** [comment]
Is it possible to rebase after https://github.com/popcornmix/omxplayer/pull/419?

**Comment by fabled** [comment]
Rebased.

**Comment by popcornmix** [comment]
Thanks. 
@kennyyy24 okay with you?

**Comment by kennyyy24** [comment]
No time to test, but yes, totally make sense. Should improve response time.

**Pull request merged**
