### PR TITLE
Remove comment in omx_wrapper\arg_parser.c

### PR DESCRIPTION
**Pull request by s8w1e2ep**
"int optind" uncommented at line 27.

### CODE REVIEW

**Comment by popcornmix** [comment]
You seem to have rather more commits that the PR title and comment describes.
Were the extra commits unintended?

**Comment by s8w1e2ep** [comment]
Sorry, I committed wrong merge.

**Comment by popcornmix** [comment]
You now have 5 commits. One of which hardcodes ``/home/pi/Ken`` into omxplayer path.
I'm not really sure what's meant to be in this pull request and what isn't...

**Comment by s8w1e2ep** [comment]
Briefly speaking, I merged the branch to the wrong place. You can delete this merge, because I don't have the permission to delete this merge.

**Pull request closed without merging**
