### PR TITLE
Debian fixes

### PR DESCRIPTION
**Pull request by tpltnt**
Hi popcornmix,

i added a check and install for 'pkg-config' and 'sudo', since they were missing on my raspbian image.
Cheers,
tpltnt

### CODE REVIEW

**Comment by Ruffio** [comment]
@popcornmix if the conflicts are solved is this PR going to be pulled?

**Comment by popcornmix** [comment]
Yes, I'm okay with merging it.

**Comment by Ruffio** [comment]
@tpltnt If you solve the conflicts, then the RP can be merged.

**Comment by tpltnt** [comment]
'pkg-config' is part of the new check already. I updated my PR, see #401

**Pull request closed without merging**
