### PR TITLE
Initial alsa support

### PR DESCRIPTION
**Pull request by fabled**
Standalone, clean and from the scratch written OMX/Alsa driver implementation for omxplayer.

### CODE REVIEW

**Comment by popcornmix** [comment]
Wow. Impressive stuff.
The good news is the code is nicely separated which makes it easier to merge.

One problem is it adds a new dependency on libspeexdsp-dev which isn't in raspbian by default. Would it be possible to use ffmpeg for resampling which we know is already required?

Building I get:
```
linux/OMXAlsa.cpp: In function 'OMX_ERRORTYPE omxalsasink_set_config(OMX_HANDLETYPE, OMX_INDEXTYPE, OMX_PTR)':
linux/OMXAlsa.cpp:986:82: error: 'strlcpy' was not declared in this scope
   strlcpy(sink->device_name, (const char*) adest->sName, sizeof sink->device_name);
                                                                                  ^
linux/OMXAlsa.cpp: In function 'OMX_ERRORTYPE omxalsasink_create(void**, OMX_PTR, OMX_CALLBACKTYPE*)':
linux/OMXAlsa.cpp:1249:64: error: 'strlcpy' was not declared in this scope
  strlcpy(sink->device_name, "default", sizeof sink->device_name);
```
Changing to strncpy allowed me to build.

When running ALSA didn't work until I added ``-o local``. Seems if hdmi is connected the ``-A`` option is ineffective by default.

With ``-o local`` I have working audio through ALSA.

**Comment by fabled** [comment]
I chose speex original due to it having simpler API to integrate than ffmpeg. IIRC, the ffmpeg resampler API does not allow changing rate scaling easily.

I build by default against musl c-library which has strlcpy. strncpy does not enforce trailing zero, but that's simple to fix.

And yes, it works by substituting the default 'local' OMX component with the alsa one. So -o local or -o both is needed in cases where -o hdmi would be assumed.

**Comment by popcornmix** [comment]
ffmpeg does allow continuous speed adjustment. That is used by Kodi on Pi (when playing with mmal).
See: https://github.com/xbmc/xbmc/blob/master/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAEResampleFFMPEG.cpp
CActiveAEResampleFFMPEG::Resample is called with ratio varying every frame to allow fine grained audio sync control. You can see the API is quite simple.

**Comment by popcornmix** [comment]
@fabled are you able to switch to using ffmpeg for resampling?

**Comment by fabled** [comment]
@popcornmix I am. But I have several high priority item I need to finish first. I think I can get to it only around late June/early July.

**Comment by popcornmix** [comment]
No problem.

**Comment by fabled** [comment]
Updated for ffmpeg with separate commits, can flatten if needed. I also just after fixing things noticed, there's separate ffmpeg helper classes. Should those be used instead?

**Comment by popcornmix** [comment]
Cool seems to be working for me. Squashing commits would be good.
Technically yes, the ffmpeg calls should go through the dll wrapper.

That is something that was inherited from kodi and isn't really needed as we link with ffmpeg explicitly. It may be removed at some point.

I also wonder if removing the ``-A`` flag and using ``-o alsa`` wouldn't make more sense.

**Comment by VittGam** [comment]
Great work!

It could also make sense to allow every combination of audio outputs to play together (eg. when using bluetooth audio in addition to local sound output).

**Comment by fabled** [comment]
@popcornmix `-o alsa` makes sense, but I want to have ability to specify the alsa device name somehow. It either needs a separate flag, or syntax to allow doing it directly in -o flag, e.g. `-o alsa:mydev`. The device name can default to `default` to simplify things.

@VittGam achieving synchronization with several audio devices is non-trivial. However, I believe ALSA might support playing back to several device with some configuration. Currently it seems BT audio works with pulseaudio only, so one would need alsa->pulse->bt routing. In any case synchronizing all audio device might be issue, especially if BT audio device (with long playback latency) is involved. IIRC, BT audio needs to be compressed, so I'm not sure if rpi cpu power is enough for that. Patches are welcome :)

**Comment by VittGam** [comment]
Actually pulseaudio supports multiple outputs with a module that combines outputs, so one could use alsa->pulse->bluetooth/usb and alsa->pulse->alsa->bcm28xx simultaneously... it should work ;) Oh and bluetooth audio works fine at least on the Pi 2, with pulseaudio.

**Comment by fabled** [comment]
@popcornmix I would like to finish this. Do you have further guidance how to do the command line parameters? Or I just draft something?

**Comment by popcornmix** [comment]
I'm happy with ``-o alsa`` for default alsa device and ``-o alsa:mydev`` for a specific alsa device.

**Comment by fabled** [comment]
Implemented and flattened. Though, now hdmi+alsa audio mode cannot be configured (it worked with `-o both -A default` before). Perhaps `-o hdmi+alsa` or similar would still need to be added?

**Comment by popcornmix** [comment]
I think handling dual audio output can be added as a later commit.
There are potentially other methods of achieving this (e.g. omxplayer just outputs to alsa and something like pulseaudio handles driving multiple devices).
Let me test this and hopefully merge it as a first step.

**Comment by popcornmix** [comment]
@fabled I've spotted a minor bug.
Play this file: https://dl.dropboxusercontent.com/u/3669512/temp/norah.wav
first with:
``omxplayer -o local norah.wav``
and second with:
``omxplayer -o alsa norah.wav``
I'm using the bcm2835 alsa driver with analogue (``amixer cset numid=3 1`` output).

Using ``-o local`` the song completes as expected. With the alsa output it stops early (you don't hear the final "again" sung). Perhaps an issue with ``OMX_BUFFERFLAG_EOS`` not waiting for audio to be rendered?

**Comment by fabled** [comment]
@popcornmix Yes, I remember I had problems getting it right, and seem to have forgotten. I did some debugging and found out the following happens on end-of-stream:

- SubmitEOS is called to send EOS marked buffer to m_omx_decoder
- IsEOS is periodically called to check if EOS has been reached on the device
- IsEOS uses GetAudioRenderingLatency() which does GetConfig(OMX_IndexConfigAudioRenderingLatency) on the hardware component

It seems that the audio hardware component never receives the EOS marked buffer. I'm not sure if this is an bug in the rpi omx core - I assume that the m_omx_decoder should not do the EOS callback until the hardware players have processed the EOS buffer. So it should forward the EOS frame to hardware device and wait for that frames return (or corresponding EOS callback from the hardware device).

And I remember implementing OMX_IndexConfigAudioRenderingLatency just to get exit more or less right, but it ignores the hardware buffer size, and just returns the internal omx queue length. This was for two reasons:

1. ALSA pauses the playback on underrun just before final buffered bytes. So giving the actual hardware buffer size would always return non-zero and prevent exit. And it's not possible to easily just flush these buffers because we don't get the EOS signal.
1. It would require allowing access to the ALSA device from two separate threads, so I just simplified this.

As workaround, it probably would make sense that the worker thread updates regularly an estimate of the real latency for OMX_IndexConfigAudioRenderingLatency (when the OMX queue is empty). And just round down to zero when there's less than, say 32 frames left or so. Would this be sufficient?

**Comment by popcornmix** [comment]
> It seems that the audio hardware component never receives the EOS marked buffer

Are you sure? I've added this assert and it fires:
```
--- a/linux/OMXAlsa.cpp
+++ b/linux/OMXAlsa.cpp
@@ -444,7 +444,7 @@ static OMX_ERRORTYPE gomx_empty_this_buffer(OMX_HANDLETYPE hComponent, OMX_BUFFE
        GOMX_COMPONENT *comp = (GOMX_COMPONENT *) hComponent;
        GOMX_PORT *port;
        OMX_ERRORTYPE r;
-
+assert(pBuffer->nFlags & OMX_BUFFERFLAG_EOS);
        if (comp->state == OMX_StateInvalid) return OMX_ErrorInvalidState;
        if (comp->state != OMX_StatePause && comp->state != OMX_StateExecuting &&
            comp->wanted_state != OMX_StateExecuting)
```

**Comment by popcornmix** [comment]
Ping @6by9 
Would you expect the EOS buffer sent from audio_decode to be seen by the arm side audio_render component? Would this be expected as a buffer received by its EmptyThisBuffer function or does it come through some event callback?

**Comment by fabled** [comment]
@popcornmix The EOS buffer is swapped by the omx client (omxplayer) and audio_decode. I believe audio_decodeshould forward this signal to downward in the stream, and wait for the eos event back until signalling eos to the client. This at least is a bug since the omx/alsa component's worker thread is not getting eos.

I tried patching the gomx_empty_this_buffer() too, but I did not seem to get EOS there. I believe your assert is inverted, since now it asserts because EOS is not set (the expression needs to be true to not generate assert).

I added there
```
CDEBUG(hComponent, 0, "nInputPortIndex=%d nFlags=%d", pBuffer->nInputPortIndex, pBuffer->nFlags);
```

But did not get any log messages where nFlags would have EOS set.

**Comment by popcornmix** [comment]
Yes, I spotted the assert was inverted and didn't actually trigger.
I traced the gpu side code and video_decode does signal the EOS which seems to cause a (OMX_EventBufferFlag, 121, 1) message to be sent to the arm, but it gets tricky to follow these messages across the arm/gpu boundary so I was hoping @6by9 might know where that should come out (or if it is not meant to).
Actually does it end up in ``COMXCoreComponent::DecoderEventHandler`` in OMXCore.cpp?

**Comment by 6by9** [comment]
I'm not fully following what is going on, and what the full problem is, but let's see how good my memory is.

OMX IL spec
3.1.1.4.5
OMX_EventBufferFlag
A component generates the OMX_EventBufferFlag event when an output port emits
a buffer with the OMX_BUFFERFLAG_EOS flag set in the nFlags field. The nData1
field of EventHandler specifies the value of the output port’s portindex field. The
nData2 field of EventHandler specifies the unaltered nFlags field containing the
end-of-stream (EOS) flag.
If a component does not propagate a stream further (e.g., the component is an audio or
video sink), then the component shall send an OMX_EventBufferFlag event for that
stream when it has finished processing a buffer with OMX_BUFFERFLAG_EOS set. The
nData1 field of EventHandler specifies the input port that received the buffer. The
nData2 field of EventHandler specifies the unaltered nFlags field containing the
EOS flag

For GPU side stuff, except when doing proprietary tunnelling, ril_top deals with the EventHandler callback when it gets given a buffer back with OMX_BUFFERFLAG_EOS set. (ril_top.c line 2271ish for those who have the firmware source).
We wouldn't expect a buffer back from the input port until the component has completed all processing on it, so that fits the spec.

audio_decode ought to pass EOS through from input to output at an appropriate point, but having a quick look it seems to have a moderately complex path which I'm not analysing now. Are you suspecting that is at fault? What codec are you using in audio_decode?

Audio_decode would seem to be the wrong component to wait on for that event - it really should be the renderer.

**Comment by fabled** [comment]
@6by9 @popcornmix That's the problem then. The GPU side should not "handle" EOS flag at all when doing tunneling. The spec (quoted above) says that only the last component in the tunnel chain (the sink) should emit the OMX_EventBufferFlag event (these events always go to the IL client - or omxplayer application in this case). The interim components (audio_decoder) should just propagate the EOS flag from incoming buffer to the outgoing buffer.

**Comment by fabled** [comment]
@6by9 We are doing software decoding, so it's passing uncompressed 2-channel 16-bit pcm audio data to omx chain.

**Comment by fabled** [comment]
Seems it could be related to the zero-length buffers. The alsa audio sink never gets zero-length buffer (except on termination when the tunneling buffers are being returned due to stop). Is it possible that the audio_decoder (or some other component between that and the sink component) does not forward received buffers to output port when nFilledLen=0, but nFlags has bits set?

**Comment by 6by9** [comment]
So we're looking at a standard OMX setup for omxplayer, but substituting audio_render for this OMX.alsa.alsa_render.

You may be right over over zero length buffers - there are some components that don't propagate them properly, but it'd take a bit of reading of the audio_decode code to work out what it does and does not do. It may also be affected by the codec in use and how it consumes data, which is why I asked.
Things do look fishy, as I can see
```
   if (in->nFilledLen)
   {
      //handle "encoded" data
   }
   else if(in->nFlags & OMX_BUFFERFLAG_EOS)
   {
      //decoder flush. Doesn't apparently do anything to pass the EOS on.
   }
```
@popcornmix it'd be the end of ad_process_output_buffer that I'd be suspicious of for when in->nFlags has EOS but nFilledLen is 0. It looks to copy through OK at first glance, but don't quite get why it could be cleared again if there is data in the buffer. I would have expected EOS and ENDOFFRAME to be valid together.

**Comment by popcornmix** [comment]
The OMX_BUFFERFLAG_EOS packet is zero length in audio_decode.
I think the problem is after ad_process_output_buffer, we do:
```
       if(out->nFilledLen || out->nFlags)
       {
          // there was something to send this time, make sure we try again as there might be more we can do.
          done = 0;
          id->callbacks.processed_buffer(id->callback_state, out, OMX_DirOutput);
          out = NULL;
       }
```
(out->nFilledLen=0, out->nFlags=OMX_BUFFERFLAG_EOS)
I think this code generates a OMX_EventBufferFlag, 121, 1 event, and discards the EOS buffer, so I don't think the arm size audio_render sees the EOS (the event went to audio_decode).

**Comment by popcornmix** [comment]
Ah - I'm looking at audio_deocode - there is actually an audio_mixer component between audio_decode and the arm side render component, so that will be where the EOS is going missing.

We do see the EOS flag, and set it on contrib.buffer->nFlags, but I'm not seeing how it gets applied to the output buffer. Not really seeing what the eos_seen and eos_sent flags do either.

**Comment by 6by9** [comment]
An audio_mixer in there moves the goalposts!

I'll agree, there doesn't appear to be any code that will ever set EOS on the output buffer.

**Comment by popcornmix** [comment]
@fabled Okay - so I've noticed that COMXAudio::IsEOS does ``m_omx_decoder.IsEOS() && GetAudioRenderingLatency()==0``. I was imagining that it would be using ``m_omx_render.IsEOS()`` which makes more sense to me, but presumably wasn't done that way before audio_mixer is not passing on the EOS flag.

As long as your alsa render compoment makes ``OMX_IndexConfigAudioRenderingLatency`` return the amount of audio alsa has queued (ideally plus any input buffers queued, although I suspect that won't matter except when we are underrunning), which should reach zero when audio is no longer sent, I suspect it will work okay.

**Comment by fabled** [comment]
@popcornmix Current `OMX_IndexConfigAudioRenderingLatency` returns the input buffer queue, but does not account for the alsa or resampler buffers. I did try querying the actual buffer sizes way back, but it hung because alsa always kept some frames buffered and instead paused on underrun. Thus latency never went to zero, and no exit.

So I can do what I suggested in my original comment as working solution, and described the limitations. Account for the alsa/ffmpeg resampler buffers, but subtract some frames from the real count. That makes us miss some bytes from being played before the end, though it will be a lot less than now.

Would be of course preferable to fix gpu side to handle eos properly. We could then fix omxplayer to wait for the eos event only, and not poll the latency at all (as minor optimization).

**Comment by fabled** [comment]
@popcornmix Updated the code now to keep cached alsa pcm state and delay. The values are updated every buffer played (when data flowing) and every 10ms when there's no data queued. It returns latency as zero when state is no longer playing (underrun or other similar problem). This seems to work around the gpu omx bug in eos passing. It looks there's about 32 frames in queues when underrun happens which is under 1ms of audio under normal sampling rate.

**Comment by popcornmix** [comment]
That seems to play the end of the file better.
Thanks for PR - I think many users will find this useful.

**Pull request merged**
