### PR TITLE
Stop showing automatically found external subtitles by default

### PR DESCRIPTION
**Pull request by mjfwalsh**
Subtitles are currently enabled by default if available. This patch hides them. They can still be toggled on and off as now, it just starts playing the file with the subtitles hidden.

### CODE REVIEW

**Comment by popcornmix** [comment]
Does changing:
https://github.com/popcornmix/omxplayer/blob/5a6f8c26d12ed42651e8ef65aec557d9f13aba8a/omxplayer.cpp#L744
to ``= -1``
achieve the same effect with ``-t 0`` on command line?

**Comment by mjfwalsh** [comment]
After a bit of testing I can't replicate issue #603. When I play a file with embedded subtitles they're off by default, unless enabled with `-t 0`.

What is an issue, is automatically found external subtitles. These are on by default with no way of turning them off from the command line.

The modified pull request will turn external subtitles off by default, unless they're specified via the `--subtitles` command line option.

**Comment by mjfwalsh** [comment]
@popcornmix in answer to you question, changing `m_subtitle_index` doesn't make any difference. The problem is [line 1141](/popcornmix/omxplayer/blob/master/omxplayer.cpp#L1141):

    if(m_subtitle_index == -1 && !m_has_external_subtitles)
        m_player_subtitles.SetVisible(false);

It make subtitles visible when `m_has_external_subtitles` is set to true so it doesn't matter when value is assigned to `m_subtitle_index`.

My (new) solution is to set `m_subtitle_index` to 0 when the the user passes `--subtitles` on the command line and ignore `m_has_external_subtitles` when hiding or not hiding the subtitles.

This retains the current position when a specific file is passed using `--subtitles` (the subtitles are displayed), but hides, by default, external subtitles found using the path.

**Comment by DanielGlaas** [comment]
Hi, I stumbled around this issue and I'm wondering why the provided patches are not yet merged. It is really a pitty that when having automatically found subtitles that omxplayer simply crashes.

**Comment by DanielGlaas** [comment]
As far as I can see your commits are not merged yet. Is this correct?
From that point of view the issue is still open until the pull request is merged.

**Pull request closed without merging**
