### PR TITLE
fixes for building in Stretch

### PR DESCRIPTION
**Pull request by yy502**
fixes https://github.com/popcornmix/omxplayer/issues/572

### CODE REVIEW

**Comment by popcornmix** [comment]
The default gcc in stretch is 6.3. That should build omxplayer just fine and you shouldn't need to install the older gcc 4.9.
Can you try changing the ``gcc-4.9 g++-4.9`` to ``gcc g++`` (in both ``REQUIRED_PKGS`` and ``CC``/``CXX``)

Also I get: ``Package libboost1.50-dev is not available, but is referred to by another package``
Again that is an old package version. stretch uses 1.62.
I think changing ``libboost1.50-dev`` to ``libboost-dev`` is correct. 

Similarly I'd change ``libusb-1.0-0-dev`` to ``libusb-dev`` (same version). However I'm not sure why omxplayer would need libusb? If it builds without it, the dependency should be removed.

**Comment by yy502** [comment]
It seems `subversion` is not needed neither.

Test compiled okay.

**Comment by popcornmix** [comment]
``make -j$(nproc)`` would be safer than ``-j 4`` (don't want 4 thread on Pi1).
There is a slight worry that the increased memory usage will cause a problem, but we may be okay.

**Comment by yy502** [comment]
cool, didn't know about `nproc` :-)

**Comment by popcornmix** [comment]
I'm not sure the ``-j `` flag will be passed to build of ffmpeg. You get this message:
``make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.``
The fix is to use ``$(MAKE)`` rather than ``make`` to launch the sub make of ffmpeg (that will pass through the jobs parameter to submake) but I think that breaks ordering (it will  try to ``make install`` in parallel with ``make``)

**Comment by yy502** [comment]
tested ok.

**Comment by popcornmix** [comment]
Could you test this commit?
http://paste.debian.net/988881/
It removes cross-compile support which hasn't worked for a long time.
It shouldn't now be necessary to patch makefiles from prepare_raspbian.sh script.

**Comment by yy502** [comment]
testing a full compilation now

**Comment by yy502** [comment]
tested ok:
```
$ ./omxplayer --version
omxplayer - Commandline multimedia player for the Raspberry Pi
        Build date: Tue, 03 Oct 2017 16:36:03 +0100
        Version   : 3a11516 [master]
        Repository: git@github.com:yy502/omxplayer.git
```

**Comment by yy502** [comment]
`-j4` really helps!

**Comment by popcornmix** [comment]
I think now we can remove the whole ``if [ -e "patch.flag" ]`` block from prepare-native-raspbian.sh script and just commit the adjusted makefiles.

**Comment by yy502** [comment]
yes, good idea.

done & tested ok

**Comment by popcornmix** [comment]
Thanks for the help with this. Looks much cleaner and build okay for me with stretch.

**Pull request merged**
