### PR TITLE
added transparency option on startup and via dbus control

### PR DESCRIPTION
**Pull request by 42loop**

### CODE REVIEW

**Comment by ktws** [comment]
Been playing with this for most of today and it works extremely well. Not seen any issues.

Your code also provided me with some pointers on how to move/resize the video layer in real-time, via dbus, without 'video stutter'. So, many thanks for that @42loop :-)

**Comment by 42loop** [comment]
@ktws : do you have a fix for the 'expensive' close/open sequence on moving/resizing the video window ? it kind of works for me, but continuously moving it, for example by mouse, it makes the player quite unstable and eventually the player would stop & exit ...

**Comment by popcornmix** [comment]
@42loop 
You should always PR from a topic branch rather than your master branch (suppose you want to make another PR and this takes a while to get merged).
Can you squash to a single commit and force push? Deleting all makefile in one commit and then adding them in a subsequent commit is bad for git history...

**Comment by ktws** [comment]
@42loop Yep, i've managed to get real-time resize/move working. I'll wait until your pull request has been accepted before pushing mine as it makes sense to map SetAlpha(0) and SetAlpha(255) to hidevideo/unhidevideo at the same time.

Quick demo of my software using it here: http://youtu.be/_KwBLSyYKG4 First video played is local, second video is  streaming from Youtube. @gkreidl ping

**Comment by gkreidl** [comment]
@42loop, @ktws 
Thanks to both of you! This might really improve my omxplayerGUI! Perhaps even resizing video from live TV streams will work again now. Eagerly waiting for the new version.

**Comment by 42loop** [comment]
I'm not very good at git, and its my first PR ever.
will take some time to meet the requirements... (eg, finally learn git)

**Comment by popcornmix** [comment]
In general you type in:
```git rebase -i HEAD~4```
follow instructions and replace the last 3 "pick"s with "squash".
You should have a single commit.
```git push -f```
when you are done, and this PR should update.

**Comment by 42loop** [comment]
ok, did it the "hard" way: there is a new pull request #331 which should be ok I hope

**Pull request closed without merging**
