### PR TITLE
Support for audio balance

### PR DESCRIPTION
**Pull request by furunkel**
This adds support for balancing left and right audio channels differently.
I don't know If you really want to pull this, but here it is.

I inadvertently staged Makefile changes, sorry for that.

### CODE REVIEW

**Comment by ivlevdenis** [comment]
Nice feature. But names of actions strange)

**Comment by Ruffio** [comment]
@furunkel will you fix the conflicts?

**Comment by furunkel** [comment]
@Ruffio, nope, sorry.

**Comment by Ruffio** [comment]
@furunkel then please clos this PR, as it can't be merged

**Pull request closed without merging**
