### PR TITLE
Implemented option --bg for custom background color

### PR DESCRIPTION
**Pull request by TheVento**
Added implementation for command line argument '--bg' to set the background color and also fill unused screen areas.

The required parameter contains 3 float numbers between 0.0 and 1.0 for each the red, green and blue component of the desired background color.
These values shall be separated by either space or by comma, similar to the syntax of the existing '--win' option.

This is an extra feature meant to add flexibility to the similar existing '-b' option which basically now has become a synonym for '--bg 0,0,0'.

Usage (syntax similar to the existing '--win')
* omxplayer --bg 0,1,0.75 <filename>

 or
* omxplayer --bg "0 1 0.75" <filename>

### CODE REVIEW

**Comment by TheVento** [comment]
Sorry i messed up the Makefile stuff first...
But this one is serious! :-)

**Comment by TheVento** [comment]
updated docs (README, usage) at last.

**Comment by popcornmix** [comment]
The implementation looks fine, but I'm unsure of how useful this is. Can you explain why you would use a coloured background?

**Comment by fcarlier** [comment]
maybe in the case where the tv is plugged on color wall and video size is smaller.

**Comment by TheVento** [comment]
i have the situation where i need to display short video loops based on multi-page PDF's, and often these have white background. also, it happens that these are not the aspect ratio of the screen, eg. generated form a A4-portrait PDF, where the screen is mounted landscape. so before I had the option of having a black background with "-b" or have no background at all without "-b". but to make it look nice, a white background would be desirable. the workaround was to fill the background with a white framebuffer image and then launching omxplayer without "-b", but this gives unsexy flickering. so I decided it would be more clever to move this inside omxplayer. instead of just creating a "--white" option found it more useful to let the user have control over the color.

**Comment by TheVento** [comment]
... btw I made a little webapp (unfinished beta) to do exactly that: generate MP4 video loops with or without transitions from multi-page PDF files: http://app.pdf2mp4converter.com/pdf2mp4v1.5/

**Comment by TheVento** [comment]
sorry for that... i am new to github.
was trying to do exactly that: 4 whitespaces instead of tabs. looks fine in my 'vim', but i will have a look again.
...but generally, got the idea of the feature (see comment above)?

**Comment by popcornmix** [comment]
You have two tabs then 8 spaces in the "--bg r,g,b" line

**Comment by TheVento** [comment]
Noob is learning :-)

**Comment by Ruffio** [comment]
@TheVento will you fix the issues?

**Comment by TheVento** [comment]
@Ruffio done;
didn't realize this topic is still on at all :)

**Comment by Ruffio** [comment]
@popcornmix good?

**Comment by jehutting** [comment]
Ho ho ho...hold on!
Are you guys aware of @obskyr pull-request #428? (@Ruffio you requested that to be merged too.)
I like obskyr implementation more as it uses the HTML hexadecimal color notation (e.g. #b955ff).
OR should this be a THIRD allowed notation for obskyr?

**Comment by obskyr** [comment]
I think float tuples are probably mostly useless... As it stands, all widely-used RGB formats are on a scale from 0 to 255. Generally, even tuple-style RGB looks like `rgb(255, 255, 255)`.

Oh, and as mentioned in #428, `VC_IMAGE_RGBX32` has a larger color space than `VC_IMAGE_RGB565`: 16,777,216 vs. 65,536 possible colors, to be exact. As far as I know there's not really a reason to go for the smaller one.

**Comment by Ruffio** [comment]
Personally I don't have any opinion on this matter, but I just don't like stalling PR if they are good to merge.

**Comment by jehutting** [comment]
..and (for what it's worth :-) with `VC_IMAGE_ARGB8888` you can have it alpha'ed.

**Comment by obskyr** [comment]
@jehutting Working on my PR, I tried `VC_IMAGE_RGBA32`. It didn't work, sadly. The background wasn't transparent regardless of what value you used for the alpha value. Besides, making just the background transparent probably isn't a very useful feature anyway...

**Comment by jehutting** [comment]
@obskyr Agree that it isn't useful but I just tried it for fun.
With `VC_IMAGE_RGBA32` you need to hassle a little bit with the position of the R,G,B and A component within the 32-bits integer; it seems to be interpreted as ABGR, whereas it name gives you the impression of RGBA?!

**Comment by obskyr** [comment]
@jehutting Oh, so you got it to work? Well then; that's weird.

**Comment by jehutting** [comment]
@obskyr continue'd in #428 as that comment belongs there.

**Comment by popcornmix** [comment]
I've implemented a simpler form of this. See: https://github.com/popcornmix/omxplayer/issues/424#issuecomment-215764331

**Pull request closed without merging**
