### PR TITLE
Extend DBUS to include video layer

### PR DESCRIPTION
**Pull request by microwavesafe**
Added DBUS commands to control the video rendering layer, this is not supported with --blank enabled

### CODE REVIEW

**Comment by Ruffio** [comment]
@microwavesafe will you fix those conflicts?

**Comment by Ruffio** [comment]
@microwavesafe any chance of fixing the conflict so it can be merged? This PR is two years old...

**Comment by Jir4** [comment]
I needed this feature so i adapted the code of this PR for the current version. Would it be intersting to add it ? Is there a need to make a new pull request ?

**Comment by dronus** [comment]
This is obsolete as of merging #651 , which also implements this functionality. Feel free to close.

**Pull request closed without merging**
