### PR TITLE
Add screenshot capabilities

### PR DESCRIPTION
**Pull request by guimeira**
I needed to take screenshots of the video that is currently playing on omxplayer for a personal project, but I couldn't find a solution that actually works, so I implemented it on the player itself.
Some parameters like the image size and the file name are configurable via command line parameters and it's possible to take screenshots using the keyboard and also using dbus.
If you think this feature can be useful for someone and want to merge it, I'll be happy to make any modifications and/or tests if you consider it necessary :)

### CODE REVIEW

**Comment by popcornmix** [comment]
Have you see https://github.com/AndrewFromMelbourne/raspi2png?
If that does what you want, then I think it's the better solution.
Makes no sense for every application to support a snapshot function, when a generic utility can handle it.

**Comment by guimeira** [comment]
I haven't seen that project, which is curious since I spent a good amount of time looking for that kind of stuff, so thank you for pointing that out!
But after comparing both solutions I still think the implementation on omxplayer itself gives better results, at least for my specific use case.
I'm using omxplayer with a JavaFX overlay, and I resize and position the video using --win, so using raspi2png I still have to remove the stuff added by JavaFX and I also get a lower resolution image, because of the resizing. Also, currently I'm only drawing around the video, but if someday I need to draw something over the video, I won't be able to remove it. On the other hand, capturing the image directly from the omxplayer pipeline gives me only the video image I need and with the original video resolution.
Finally, I'm not sure if it's an expected behavior or if it's happening only here, but when I run raspi2png the screen turns black for a short amount of time. It's not that bad, but I think a more seamless way of capturing the screenshots gives a better user experience.
So, I don't think they are two solutions for the same problem. They are more like two different tools for two different jobs.
But I know that omxplayer has its very specific goals, so I totally understand your point of view.

**Comment by Ruffio** [comment]
@guimeira should we close this RP?

**Comment by guimeira** [comment]
Yes :)

**Pull request closed without merging**
