### PR TITLE
Fix Cppcheck reported issues and revert video/audio player instantiation order

### PR DESCRIPTION
**Pull request by brunogm0**
I decided to put these two together: 
fix almost all cppcheck issues;
Invert audio and video player Open(), to change allocation order for the buffers;

The second helps with #230 , it not solves completely because too little memory will trigger, but is much more easy to dynamically manage video_fifo size as the number of audio buffers is fixed.

### CODE REVIEW

**Comment by Ruffio** [comment]
@brunogm0 is this an issue?

**Comment by brunogm0** [comment]
I dont hava a RPi to test anymore.  The purpose of the instantiation order was to allow audio to play when the video buffer is to small or initialization error.    
I will run the newer cppcheck on the latest source and report back but takes a long time to run it.

**Comment by Ruffio** [comment]
@brunogm0 any news?

**Comment by brunogm0** [comment]
Sorry the delay, but  there are a bunch of errors.
[omxplayer-master.zip](https://github.com/popcornmix/omxplayer/files/271247/omxplayer-master.zip)

**Pull request closed without merging**
