### PR TITLE
Fix white flash at the end of playback. (#658)

### PR DESCRIPTION
**Pull request by jehutting**

### CODE REVIEW

**Comment by popcornmix** [comment]
So, the problem is that SubmitEOS is called when demuxer reaches end of file, but not all the encoded frames have been submitted to decoder.

``m_packets`` may contain dozens of encoded frames of data at the point SubmitEOS is called. We want those to all be submitted to decoder before the SubmitEOS is called.

I don't think this PR achieves that. I think what we want is for the EOS message to be pushed into the m_packets queue and then handled by the ``Process`` thread after all the frames have been submitted to decoder.

How easily can you reproduce the failure mode? I could suggest a patch for testing.

**Comment by popcornmix** [comment]
This is what I was thinking of:
http://paste.ubuntu.com/p/9WSsP256DN/

**Comment by jehutting** [comment]
_So, the problem is that SubmitEOS is called when demuxer reaches end of file, but not all the encoded frames have been submitted to decoder._  Yes that is what I am trying to say.

The way I see it is that each packet popped from ```m_packets``` is fully emptied to the m_omx_decoder. First, ```OMXPlayerVideo::Decode``` gets in a loop to wait for enough free space of ```m_decoder```. If so ```m_decoder->Decode``` is called.  This function sends all data of the packet  (through ```while dmuxer_bytes```) to the m_omx_decoder. (by the way, if ```GetInputBuffer``` fails all remaining data of the packet will be lost).  No matter if the emptying to m_omx_decoder went fine or not, after ```OMXPlayerVideo.Decode``` the packet is assumed to be fully decoded. The packet size is subtracted from the ```m_cached_size```. When all ```m_packets``` packets are decoded a ```m_cached_size == 0``` reflects that. A ```Submit EOS``` will be called which will finalize the playing by directly (so not through ```m_packets```) sending a ```OMX_BUFFERFLAG_EOS``` to the decoder. Bypassing ```m_packets``` is OK for me, as ```OMXPlayerVideo::Process/Decode```and ```OMXVideo::Decode``` has already decoded the last (video) packet/frames, and all data sent to ```m_omx_decoder```.

So my PR achieves it perfectly by simply decrementing ```m_cached_size``` after the packet is decoded, and not beforehand it is decoded.

Take the video posted in issue #658 (radar.mp4) or #250 (synctest.mp4).

**Comment by popcornmix** [comment]
Calling SubmitEOS in the middle of the video stream (with subsequent packets) is a bad thing to do. It flushes the video decoder (to ensure final frames are pushed out). Subsequent video frames will be decoded without the reference frames they depend on (potentially causing the white flash).

Kodi works in a similar way of passing the EOS packet through the decode queue so the SubmitEOS call occurs after the final frame of video is submitted to decoder.

I don't think you can guarantee that SubmitEOS will always be called after the final frame of video in your patch. If the video decode is slow (e.g. high bitrate / multiple reference frames) we may submit frames faster than decoder can consume them and m_packets may contain a lot of packets of data.

Remember ``Process`` where we submit packets to decoder is in a separate thread to ``OMXPlayerVideo::SubmitEOS``.

Can you test the samples with my patch?

**Comment by jehutting** [comment]
My PR doesn't call ```SubmitEOS``` while the ```m_packets```  are being decoded.

From omxplayer.cpp (the main thread)
```
    if(m_omx_reader.IsEof() && !m_omx_pkt)
    {
      // demuxer EOF, but may have not played out data yet
      if ( (m_has_video && m_player_video.GetCached()) ||
           (m_has_audio && m_player_audio.GetCached()) )
      {
        OMXClock::OMXSleep(10);
        continue;
      }
      if (!m_send_eos && m_has_video)
        m_player_video.SubmitEOS();
      if (!m_send_eos && m_has_audio)
        m_player_audio.SubmitEOS();
      m_send_eos = true;
      if ( (m_has_video && !m_player_video.IsEOS()) ||
           (m_has_audio && !m_player_audio.IsEOS()) )
      {
        OMXClock::OMXSleep(10);
        continue;
      }
``` 

Only when ```m_player_video.GetCached()``` returns 0 which is when ```m_cached_size == 0```,  omxplayer submits the EOS. In my opinion :-) there is nothing wrong with this as ```Process``` isn't doing anything any more when ```m_packets``` is empty (/all frames are sent to the decoder). The ```SubmitEOS```  _always_ places the EOS nicely behind the last decoded frame.

At the end you basicly do the same: only you push an extra ```nullptr``` packet, and when ```Process```  pops that packet do the actual EOS; also behind the last decoded frame. In my opinion (again with a :-)) unnecessary way to do. _(```OMXReader::FreePacket``` already handle null pkt; if you persist on using ```if (pkt)``` just place it before the ```pop_front``` call.)__

And yes, your patch works fine (too :-)).

But hey... I go whatever your choice will be, just make a choice and -please- do a commit. Thanks in advance.

**Comment by popcornmix** [comment]
I see. There is a hack in omxplayer.cpp which delays sending the EOS message which makes what happens in OMXPlayerVideo somewhat safer.
My fix makes that hack no longer required.
I've pushed my fix and removed the hack. Let me know if you spot any problems with this.

Do you have any files where the change to using render rather than decode for ``IsEOS`` check is beneficial? I don't mind the idea of that change, but as any change has a small chance of a regression, I'd like to know there is a definite benefit in some case.

**Comment by jehutting** [comment]
Your mod in ```omxplayer.cpp``` looks fine too me.

My ```OMXAudio::IsEOS``` mod is more in analogy to the ```OMXVideo::IsEOS```. I assume that there are some buffers involved between the decoder and the renderers. I would like to assure that the jack/hdmi/alsa audio renderers are done with the outputting before tearing everything down.

I don't have a file which proofs the necessity of the mod.

Thanks again for the push!

**Comment by popcornmix** [comment]
Thanks for helping identify where the problem was.

**Pull request closed without merging**
