### PR TITLE
Fix #313 by catching when unhide occurs and explicitly re-opening video player

### LINKED ISSUE #313: setvideopos doesn't work any more
In latest release from http://omxplayer.sconde.net/ the dbus command setvideopos doesn't work any more. The video gets lost.
I'm using that a lot in omxplayerGUI, when a window is moved or resized or the display format is changed.
It works with the default Raspbian version.

### PR DESCRIPTION
**Pull request by tdicola**
This fixes a bug with the hide & unhide video actions, #313.  The issue is that hide will close the video player component and unhide will cause a seek which expects the video player to be re-opened.  However an optimization was made to seek so that it wouldn't close and re-open the video player (#322), and this ends up breaking unhide.

As a fix this change catches the case where unhide occurs and does an explicit re-open of the video player.  For all other seeks (like looping, user initiated seek, etc.) the quick reset occurs instead of a full close & open.

I tested this by playing a video and using the dbuscontrol.sh to run hide, unhide, and setvideopos.  Before the fix hide would work but neither unhide or setvideopos would work as expected.  After the fix the same commands work as expected--hide will stop displaying the video, unhide will show the video again, and setvideopos will change what area of the screen displays the video.

### CODE REVIEW

**Comment by tdicola** [comment]
Just updated to remove that redundant part and gave it a quick test to make sure hide, unhide, and setvideopos worked as expected.

**Comment by popcornmix** [comment]
Can you squash the two commits and force push?

**Comment by tdicola** [comment]
No problem, should be one commit now.  Let me know if there are any issues, thanks!

**Comment by 42loop** [comment]
fix #313 makes the dbus functions work, but breaks the loop functionality

**Comment by popcornmix** [comment]
@42loop are you saying that loop functionality is broken with this PR?
We know #313 broke it, but this PR should fix it.

**Comment by 42loop** [comment]
sorry, got the wrong number(313). but anyway, pull request #326, as stated above, fixes the dbus issue but loop does not work

**Comment by 42loop** [comment]
sorry again, i restarted with a fresh copy including compiling the new ffmeg, and  the pull request #326 works.

**Pull request merged**
